AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: s3-lambda-transcribe

Parameters:
  AudioBucketName:
    Type: String
    Default: 'audio-bucket-2a7ee00c-e8d9'
  TranscribeBucketName:
    Type: String
    Default: 'transcribe-bucket-2a7ee00c-e8d9'
  ConvertBucketName:
    Type: String
    Default: 'convert-bucket-2a7ee00c-e8d9'
  DefaultLanguageCode:
    Type: String
    Description: 'The language code of your audio file'
    Default: 'en-US'
    AllowedValues: ['af-ZA','ar-AE','ar-SA','cy-GB','da-DK','de-CH','de-DE','en-AB','en-AU','en-GB','en-IE','en-IN','en-US','en-WL','es-ES','es-US','fa-IR','fr-CA','fr-FR','ga-IE','gd-GB','he-IL','hi-IN','id-ID','it-IT','ja-JP','ko-KR','ms-MY','nl-NL','pt-BR','pt-PT','ru-RU','ta-IN','te-IN','tr-TR','zh-CN','zh-TW','th-TH','en-ZA','en-NZ']

Globals:
  Function:
    Timeout: 10

Resources:
  AudioBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref AudioBucketName

  TranscribeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref TranscribeBucketName

  ConvertBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ConvertBucketName

  TranscribeFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: transcribeFunction/
      Handler: app.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Environment:
        Variables:
          TranscribeBucket: !Ref TranscribeBucket
          DefaultLanguageCode: !Ref DefaultLanguageCode
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref AudioBucketName
        - S3CrudPolicy:
            BucketName: !Ref TranscribeBucketName
        - Statement:
          - Effect: Allow
            Resource: '*'
            Action:
              - transcribe:StartTranscriptionJob
              - cloudwatch:GetMetricStatistics
              - cloudwatch:ListMetrics
      Events:
        FileUpload:
          Type: S3
          Properties:
            Bucket: !Ref AudioBucket
            Events: s3:ObjectCreated:*
            Filter: 
              S3Key:
                Rules:
                  - Name: suffix
                    Value: '.mp3'

  ConvertFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: convertFunction/
      Handler: app.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Environment:
        Variables:
          ConvertBucket: !Ref ConvertBucket
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref TranscribeBucketName
        - S3CrudPolicy:
            BucketName: !Ref ConvertBucketName
      Events:
        FileUpload:
          Type: S3
          Properties:
            Bucket: !Ref TranscribeBucket
            Events: s3:ObjectCreated:*
            Filter: 
              S3Key:
                Rules:
                  - Name: suffix
                    Value: '.json'       

Outputs: 
  S3AudioBucketName:
    Description: Audio S3 bucket
    Value: !Ref AudioBucket
  S3TranscribeBucketName:
    Description: Transcription S3 Bucket
    Value: !Ref TranscribeBucket
  S3ConversionBucketName:
    Description: Converted transcript bucket
    Value: !Ref ConvertBucket
